### ISSUE TITLE
False positive: Unconnected cycleway

### ISSUE THREAD

**Issue by don-vip** [osm-fr/osmose-backend#734]
`entrance=yes` and `noexit=yes` way end nodes should be excluded from the "Unconnected cycleway" check.

Examples:
- http://osmose.openstreetmap.fr/fr/error/bb4e9346-5b5c-dba7-305e-f3c245c83073
- http://osmose.openstreetmap.fr/fr/error/e93b8a4f-b1d8-6a8c-43dd-3f5c328f96be

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?item=1210&class=1

**Comment by frodrigo** [comment]
Should be good.

**Comment by danfos** [comment]
Looks to me like the fix worked for a few days but somehow was reverted later:

http://osmose.openstreetmap.fr/en/errors/graph.png?item=1210&class=1

For example:
* http://osmose.openstreetmap.fr/en/error/a8d95779-e7b2-6b22-cf31-efdf3d96bd39
* http://osmose.openstreetmap.fr/en/error/6f1bf2df-149e-cb11-0a3e-268789536278

**Comment by frodrigo** [comment]
The commit https://github.com/osm-fr/osmose-backend/commit/af6930f672df53258a4bc1a5d94a493d864a6150
is still here
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_deadend.py#L45-L47

**Comment by frodrigo** [comment]
Was merged on 1st Feb, when the value back to max
http://osmose.openstreetmap.fr/en/errors/graph.png?item=1210&class=1&start_date=2019-12
No sure about the lower part.

**Comment by danfos** [comment]
Thanks for re-opening.

Yes, strange, before the commit was merged, the number did go down but after it was merged it did go back to the old value...

**Comment by frodrigo** [comment]
The donw is linked to an other issue. All analyze have the same errornous
data.

Do you see it working, or you are unsure at that?

**Comment by danfos** [comment]
I do not ever check, I saw the problem before 2020 and just stumbled on this Issue

**Comment by danfos** [comment]
Meant to say "I did not check" so I am unsure it did ever work.

**Comment by danfos** [comment]
On what is the problem, I would write the additional conditions as:

```
    JOIN nodes ON
        nodes.id = way_ends.nid AND
        NOT(nodes.tags?'highway' AND nodes.tags->'highway' = 'turning_circle') AND
        NOT(nodes.tags?'entrance' AND nodes.tags->'entrance' != 'no') AND
        NOT(nodes.tags?'noexit' OR nodes.tags->'noexit' != 'no')
```

NOT has a higher [operator precedence](https://mariadb.com/kb/en/operator-precedence/) than AND

**Comment by frodrigo** [comment]
It is not the point, it is the same.
```
!a or !b <=> !(a and b)
```

**Comment by danfos** [comment]
Yes, I that logic but, but focusing on the last line:

`NOT(nodes.tags?'noexit' OR nodes.tags->'noexit' != 'no')`

and

`(NOT nodes.tags?'noexit' OR nodes.tags->'noexit' != 'no')`

are not equivalent, the difference is in the last part, the current code is missing a not or the `!=` should become a `=`. In any case, I find the first form easier to read.

The same problem is present for entrance.

**Comment by frodrigo** [comment]
You are right. It should be
```sql
        (NOT nodes.tags?'highway' OR nodes.tags->'highway' = 'turning_circle') AND
        (NOT nodes.tags?'entrance' OR nodes.tags->'entrance' = 'no') AND
        (NOT nodes.tags?'noexit' OR nodes.tags->'noexit' = 'no')
```

**Comment by danfos** [comment]
Nice, problem found.

When fixing this, it would be great to include amenity=bicycle_parking to be also excluded.

**Comment by frodrigo** [comment]
Duplicate #627

**Comment by frodrigo** [comment]
*  Remove deal with highway=turning_circle for cycleway
* Ignore amenity=bicycle_parking in analyser_osmosis_highway_deadend

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/graph.png?item=1210&class=1&country=netherland*&start_date=2020-05

Fix deployed. It is now ok for you?

**Comment by danfos** [comment]
The number in the graph did go down much less than expected, only a few procent.

Had a look at the problems reported in http://osmose.openstreetmap.fr/en/errors/?source=4709&item=1210&class=1 but I still see errors being reported for noexit=yes

* http://osmose.openstreetmap.fr/en/error/a8d95779-e7b2-6b22-cf31-efdf3d96bd39
* http://osmose.openstreetmap.fr/en/error/d5af7cbb-24a8-8a1f-c86b-1bec9dc8e1ba

Also still problem reported for amenity=bicycle_parking

* http://osmose.openstreetmap.fr/en/error/97cb0cc6-8009-a482-b464-1fb56b6aaff1
* http://osmose.openstreetmap.fr/en/error/8b60d3ae-be71-755f-36ad-6524f70f3e6c

And also for entrance != no:

* http://osmose.openstreetmap.fr/en/error/49535e1e-9aa6-a579-0eb0-407eb9602cfc

Does it takes longer for these changes to ripple through or is there still something wrong with the code?

**Comment by danfos** [comment]
It looks to me that in the code changes became active, a drop of about 10% begin this month in the errors reported for the Netherlands and the links above give now a 410 Gone. Did some more checks but could not find the problems reported above anymore.

The next problem I see is cycleways ending on an area mapped as amenity=bicycle_parking. Some can be "solved" by adding an entrance=yes but some not. But that is a new issue and it looks to me this issue can be marked as solved.

**Comment by frodrigo** [comment]
Ok. Open a new one if required, but It may be already exists.
